[theme]
primaryColor = "#1a75ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = false

[runner]
magicEnabled = false  # Disable magic commands for stability
